# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggetsapp', '0002_nugget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugget_user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nugget_user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
